//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_PHONE_SERVICE.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(export_bill))]
    [KnownType(typeof(product))]
    
    public partial class export_bill_detail
    {
    	[DataMember]
        public int id_product { get; set; }
    	[DataMember]
        public int id_export_bill { get; set; }
    	[DataMember]
        public int number { get; set; }
    
    	[DataMember]
        public virtual export_bill export_bill { get; set; }
    	[DataMember]
        public virtual product product { get; set; }
    }
}
