//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_PHONE_SERVICE.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(import_bill_detail))]
    [KnownType(typeof(manufacturer))]
    
    public partial class import_bill
    {
        public import_bill()
        {
            this.import_bill_detail = new HashSet<import_bill_detail>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public System.DateTime date { get; set; }
    	[DataMember]
        public int id_manufacturer { get; set; }
    	[DataMember]
        public decimal total_price { get; set; }
    
    	[DataMember]
        public virtual ICollection<import_bill_detail> import_bill_detail { get; set; }
    	[DataMember]
        public virtual manufacturer manufacturer { get; set; }
    }
}
