//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_PHONE_SERVICE.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(export_bill_detail))]
    [KnownType(typeof(import_bill_detail))]
    [KnownType(typeof(manufacturer))]
    [KnownType(typeof(save))]
    
    public partial class product
    {
        public product()
        {
            this.export_bill_detail = new HashSet<export_bill_detail>();
            this.import_bill_detail = new HashSet<import_bill_detail>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int id_manufacturer { get; set; }
    	[DataMember]
        public int id_save { get; set; }
    	[DataMember]
        public string name { get; set; }
    	[DataMember]
        public string product_info { get; set; }
    	[DataMember]
        public decimal sale_price { get; set; }
    	[DataMember]
        public int number { get; set; }
    	[DataMember]
        public string image { get; set; }
    
    	[DataMember]
        public virtual ICollection<export_bill_detail> export_bill_detail { get; set; }
    	[DataMember]
        public virtual ICollection<import_bill_detail> import_bill_detail { get; set; }
    	[DataMember]
        public virtual manufacturer manufacturer { get; set; }
    	[DataMember]
        public virtual save save { get; set; }
    }
}
